-- * Creating table
-- CREATE TABLE book (
--     id INTEGER PRIMARY KEY,
--     title VARCHAR(200) NOT NULL,
--     publication_date DATE,
--     author_id INTEGER REFERENCES author(id) On DELETE CASCADE
-- );
 -- DROP TABLE IF EXISTS public.author;
 -- CREATE TABLE public.author (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--   birth_date DATE
-- );
 -- * Inseting value

-- INSERT INTO public.book (id, title, publication_date, author_id)
-- VALUES
--   (1, 'Naruto Vol. 1', '2000-03-03', 1),
--   (2, 'Naruto Vol. 2', '2000-04-04', 1),
--   (3, 'Sasuke Story', '2009-05-01', 2),
--   (4, 'Sakura Guide', '2010-01-10', 3),
--   (5, 'Kakashi ANBU', '2014-09-01', 4),
--   (6, 'Hinata Chronicles', '2011-02-14', 5);



-- SELECT * from public.author
-- SELECT * FROM public.book;

-- * Join para ver el titulo y nombre
SELECT book.title, author.name from book JOIN author
ON book.author_id = author_id;
