-- * Creating table
-- DROP TABLE IF EXISTS public.book;
-- CREATE TABLE public.book (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   title VARCHAR(200) NOT NULL,
--   publication_date DATE,
--   author_id INTEGER REFERENCES public.author(id) ON DELETE CASCADE
-- );

-- DROP TABLE IF EXISTS public.author;
-- CREATE TABLE public.author (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name VARCHAR(100) NOT NULL,
--   birth_date DATE
-- );

 -- * Inseting value

-- INSERT INTO public.book (id, title, publication_date, author_id)
-- VALUES
--   (1, 'Naruto Vol. 1', '2000-03-03', 1),
--   (2, 'Naruto Vol. 2', '2000-04-04', 1),
--   (3, 'Sasuke Story', '2009-05-01', 2),
--   (4, 'Sakura Guide', '2010-01-10', 3),
--   (5, 'Kakashi ANBU', '2014-09-01', 4),
--   (6, 'Hinata Chronicles', '2011-02-14', 5);


-- INSERT INTO public.author (name, birth_date) VALUES
--   ('Naruto Uzumaki', '1999-10-10'),
--   ('Sasuke Uchiha', '1999-07-23'),
--   ('Sakura Haruno', '2000-03-28'),
--   ('Kakashi Hatake', '1991-09-15'),
--   ('Hinata Hyuga', '1999-12-27');


-- SELECT * from public.author
-- SELECT * FROM public.book;

-- INSERT INTO public.book (title, publication_date, author_id) VALUES
--   ('Naruto Vol. 1', '2000-03-03', 1),
--   ('Naruto Vol. 2', '2000-04-04', 1),
--   ('Sasuke Story', '2009-05-01', 2),
--   ('Sakura Guide', '2010-01-10', 3),
--   ('Kakashi ANBU', '2014-09-01', 4),
--   ('Hinata Chronicles', '2011-02-14', 5);


-- * Join para ver el titulo y nombre
-- SELECT book.title, author.name from book JOIN author
-- ON book.author_id = author_id;


-- actualizar dartos
-- SELECT * from author



-- UPDATE public.author SET name = 'Willian metelien' WHERE id = 1;



-- contar 
-- SELECT COUNT(*) FROM public.book;

-- SELECT * FROM author ORDER BY publication_date DESC;  --descendente

-- SELECT * FROM public.author WHERE name like 'Willian%';


-- * Consultas anidadas

-- SELECT title FROM book WHERE author_id = (
--     SELECT id FROM author WHERE name = 'Madara'
-- );



--  ! Eliminando las tablas
-- DROP TABLE IF EXISTS public.book;
-- DROP TABLE IF EXISTS public.author;


-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema='public'
--   AND table_name LIKE 'minilibrary_%'
-- ORDER BY table_name;


-- SELECT * FROM public.minilibrary_author WHERE name LIKE 'Ja%';
SELECT * FROM public.minilibrary_book WHERE author_id = 208;

-- SELECT "minilibrary_author"."id", "minilibrary_author"."name", "minilibrary_author"."birth_date" FROM "minilibrary_author"
