# Generated by Django 6.0.2 on 2026-02-08 00:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Biografía')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('publication_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Publicación')),
                ('pages', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Páginas')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Precio')),
                ('stock', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad en Stock')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='minilibrary.author', verbose_name='Autor')),
                ('genres', models.ManyToManyField(related_name='books', to='minilibrary.genre', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Resumen')),
                ('cover_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL de Portada')),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés'), ('jp', 'Japonés'), ('fr', 'Francés'), ('de', 'Alemán')], default='es', max_length=2, verbose_name='Idioma')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editorial')),
                ('edition', models.CharField(blank=True, max_length=50, null=True, verbose_name='Edición')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='minilibrary.book', verbose_name='Libro')),
            ],
            options={
                'verbose_name': 'Detalle de Libro',
                'verbose_name_plural': 'Detalles de Libros',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Préstamo')),
                ('due_date', models.DateTimeField(verbose_name='Fecha de Devolución')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución Real')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('active', 'Activo'), ('returned', 'Devuelto'), ('overdue', 'Vencido')], default='pending', max_length=10, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='minilibrary.book', verbose_name='Libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-loan_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Calificación')),
                ('comment', models.TextField(verbose_name='Comentario')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='minilibrary.book', verbose_name='Libro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='minilibrary_title_cd826e_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='minilibrary_author__003814_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['publication_date'], name='minilibrary_publica_74e681_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'book')},
        ),
    ]
