# Generated by Django 6.0.1 on 2026-01-29 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0006_loan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='user_id',
            new_name='user',
        ),
    ]
