# Generated by Django 6.0.1 on 2026-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0007_rename_book_id_loan_book_rename_user_id_loan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_returned',
            field=models.DateTimeField(null=True),
        ),
    ]
