# Generated by Django 6.0.1 on 2026-01-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0009_alter_loan_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='is_returned',
            field=models.BooleanField(null=True),
        ),
    ]
