# Generated by Django 6.0.1 on 2026-01-29 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0011_alter_loan_is_returned'),
    ]

    operations = [
    ]
