# Generated by Django 6.0 on 2026-01-20 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minilibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'test_table',
                'managed': False,
            },
        ),
        migrations.RenameField(
            model_name='book',
            old_name='Author',
            new_name='author',
        ),
    ]
